language: node_js
cache: npm

node_js:
  - 8
  - 10
  - 12

sudo: false

branches:
  only:
    - master
    - /^greenkeeper/.*$/

env:
  matrix:
    - SEQUELIZE_VERSION=4
    - SEQUELIZE_VERSION=5

  global:
    - TEST=1

matrix:
  fast_finish: true

  include:
    - node_js: 10
      env: TEST=0 LINT=1

    - node_js: 10
      env: TEST=0 COVERAGE=1

before_script:
 - sh -c "if [ '$TEST' = '1' ]; then npm install sequelize@^$SEQUELIZE_VERSION.0.0; fi"

script:
  - sh -c "if [ '$TEST' = '1' ]; then npm run test; fi"
  - sh -c "if [ '$LINT' = '1' ]; then npm run lint; fi"
  - sh -c "if [ '$COVERAGE' = '1' ]; then npm run coverage; fi"

after_success:
  - if [[ $COVERAGE == 1 ]]; then bash <(curl -s https://codecov.io/bash); fi

deploy:
  script:
    - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
    - npm run release

notifications:
  email:
    on_success: never
    on_failure: always
